{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "a7cd4db5-d1ab-423a-9d75-7c168f5bfbb3",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Seed set to 56\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "56"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from tqdm import tqdm\n",
    "import timm\n",
    "import torch\n",
    "from torch import nn\n",
    "from PIL import Image\n",
    "from torch.utils.data import DataLoader, Dataset\n",
    "import torch.backends.cudnn as cudnn\n",
    "import wandb\n",
    "import pytorch_lightning as pl\n",
    "from torch.nn.utils.rnn import pad_sequence,pack_padded_sequence\n",
    "from transformers import AutoTokenizer,T5ForConditionalGeneration\n",
    "from sklearn.model_selection import train_test_split\n",
    "from rdkit import RDLogger,Chem\n",
    "from rdkit.Chem import AllChem,DataStructs\n",
    "import torch.nn.functional as F\n",
    "import os\n",
    "from rdkit.DataStructs import TanimotoSimilarity\n",
    "from Levenshtein import distance as levenshtein_distance\n",
    "pl.seed_everything(56)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "5d6cdb06-64ee-4752-8b35-9b960824c754",
   "metadata": {},
   "outputs": [],
   "source": [
    "RDLogger.DisableLog('rdApp.*')\n",
    "os.environ[\"TOKENIZERS_PARALLELISM\"] = \"false\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "fc5e0025-e02a-4e90-9217-c3230205660e",
   "metadata": {},
   "outputs": [],
   "source": [
    "class CFG:\n",
    "    wandb=True\n",
    "    model='sagawa/CompoundT5'\n",
    "    train_path = 'train_t5_df.csv'\n",
    "    train_folder = './train/'\n",
    "    betas=(0.9, 0.999)\n",
    "    img_size = 512\n",
    "    max_pred_len = 128\n",
    "    val_split_size = 0.2\n",
    "    scheduler = None\n",
    "    eps=1e-6\n",
    "    num_workers = 12\n",
    "    batch_size = 64\n",
    "    lr=2e-5\n",
    "    weight_decay = 0.01\n",
    "    fine_tune_encoder = False\n",
    "    max_epoches=20\n",
    "    seed=56"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "2eea8356-67d4-4c09-a1ee-b7feb9a9f3ef",
   "metadata": {},
   "outputs": [],
   "source": [
    "class PLDataset(Dataset):\n",
    "    def __init__(self, df, tokenizer):\n",
    "        super().__init__()\n",
    "        self.df = df\n",
    "        self.tokenizer = tokenizer\n",
    "\n",
    "    def __len__(self):\n",
    "        return len(self.df)\n",
    "\n",
    "    def __getitem__(self, idx):\n",
    "        input_l = self.df.iloc[idx]['refs']\n",
    "        label = self.df.iloc[idx]['smiles']\n",
    "        input_enc = self.tokenizer.encode_plus(input_l, padding='max_length',max_length=128, truncation=True, return_tensors='pt')\n",
    "        label_enc = self.tokenizer.encode_plus(label, padding='max_length',max_length=128, truncation=True, return_tensors='pt')\n",
    "        return {'input_ids':input_enc.input_ids.squeeze(0),\n",
    "                'attention_mask':input_enc.attention_mask.squeeze(0),\n",
    "                'label':label_enc.input_ids.squeeze(0),}\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "05d289e1-9abc-4c70-8520-be6fee67ccc0",
   "metadata": {},
   "outputs": [],
   "source": [
    "class PLDataModule(pl.LightningDataModule):\n",
    "    def __init__(self,tokenizer):\n",
    "        super().__init__()\n",
    "        self.cfg = CFG()\n",
    "        self.is_setup = False\n",
    "        self.tokenizer = tokenizer\n",
    "        \n",
    "    def prepare_data(self):\n",
    "        self.train_data = pd.read_csv(CFG.train_path)\n",
    "        \n",
    "    def setup(self, stage: str):\n",
    "        self.train_df, self.val_df = train_test_split(self.train_data, test_size=self.cfg.val_split_size,random_state=self.cfg.seed)\n",
    "        self.train_df = self.train_df.reset_index(drop=True)\n",
    "        self.val_df = self.val_df.reset_index(drop=True)\n",
    "        self.train_dataset = PLDataset(self.train_df,self.tokenizer)\n",
    "        self.val_dataset = PLDataset(self.val_df,self.tokenizer)\n",
    "        self.is_setup = True\n",
    "    \n",
    "    def train_dataloader(self):\n",
    "        return DataLoader(self.train_dataset,\n",
    "                          batch_size=self.cfg.batch_size,\n",
    "                          num_workers=self.cfg.num_workers,\n",
    "                          pin_memory=True,\n",
    "                          shuffle=True)\n",
    "    \n",
    "    def val_dataloader(self):\n",
    "        return DataLoader(self.val_dataset,\n",
    "                          batch_size=self.cfg.batch_size,\n",
    "                          num_workers=self.cfg.num_workers,\n",
    "                          pin_memory=True,\n",
    "                          shuffle=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "86aa7e34-7e2a-48ab-86dd-5b19edef7085",
   "metadata": {},
   "outputs": [],
   "source": [
    "def char_accuracy(y_p,y):\n",
    "    y_p,y = list(y_p),list(y)\n",
    "    ln = min(len(y_p),len(y))\n",
    "    score = 0\n",
    "    for i in range(ln):\n",
    "        if y_p[i] == y[i]:\n",
    "            score += 1\n",
    "    return score / max(len(y_p),len(y))\n",
    "\n",
    "def accuracy(y_p,y):\n",
    "    if y_p == y:\n",
    "        return 1\n",
    "    return 0\n",
    "\n",
    "def correct_part(y_p):\n",
    "    if Chem.MolFromSmiles(y_p) is None:\n",
    "        return 0\n",
    "    else:\n",
    "        return 1\n",
    "\n",
    "def tanimoto(y_p,y):\n",
    "    try:\n",
    "        mol1 = Chem.MolFromSmiles(y_p)\n",
    "        mol2 = Chem.MolFromSmiles(y)\n",
    "    \n",
    "        vec_1 = AllChem.RDKFingerprint(mol1)\n",
    "        vec_2 = AllChem.RDKFingerprint(mol2)\n",
    "        return DataStructs.TanimotoSimilarity(vec_1,vec_2)\n",
    "    except:\n",
    "        return 0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "2ff8d1c9-6818-48c3-a907-c8e2917689db",
   "metadata": {},
   "outputs": [],
   "source": [
    "class AverageMeter:\n",
    "    def __init__(self):\n",
    "        self.reset()\n",
    "\n",
    "    def reset(self):\n",
    "        self.preds = []\n",
    "        self.targets = []\n",
    "\n",
    "    def update(self,preds,targets):\n",
    "        self.preds += preds\n",
    "        self.targets += targets\n",
    "    \n",
    "    def calc_metrics(self):\n",
    "        f = dict()\n",
    "        \n",
    "        f['char_acc'] = np.mean([char_accuracy(x,y) for x,y in zip(self.preds,self.targets)])\n",
    "        f['acc'] = np.mean([accuracy(x,y) for x,y in zip(self.preds,self.targets)])\n",
    "        f['corrent_part'] = np.mean([correct_part(x) for x in self.preds])\n",
    "        f['tanimoto'] = np.mean([tanimoto(x,y) for x,y in zip(self.preds,self.targets)])\n",
    "        \n",
    "        return f"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "11b16e60-4fdf-4f13-bf52-17aab8271b1f",
   "metadata": {},
   "outputs": [],
   "source": [
    "class PLModule(pl.LightningModule):\n",
    "    def __init__(self,model,tokenizer):\n",
    "        super().__init__()\n",
    "        self.cfg = CFG()\n",
    "        self.avg_meter = AverageMeter()\n",
    "        self.model = model\n",
    "        self.tokenizer = tokenizer\n",
    "        \n",
    "    def forward(self,input_ids,attention_mask,label):\n",
    "        return self.model(input_ids=input_ids,attention_mask=attention_mask,labels=label)   \n",
    "\n",
    "    def training_step(self, batch, _):\n",
    "        loss = self(**batch).loss\n",
    "        self.log_dict({'train_loss':loss.item()})\n",
    "        return loss\n",
    "        \n",
    "    def validation_step(self, batch, _):\n",
    "        labels = batch['input_ids'].detach().cpu().numpy()\n",
    "        labels = [self.tokenizer.decode(ids, skip_special_tokens=True) for ids in labels]\n",
    "        \n",
    "        logits = self.model.generate(\n",
    "            batch['input_ids'],\n",
    "            num_beams=1,\n",
    "            max_length=128\n",
    "        )\n",
    "        \n",
    "        logits = logits.detach().cpu().numpy()\n",
    "        logits = [self.tokenizer.decode(ids, skip_special_tokens=True) for ids in logits]\n",
    "        self.avg_meter.update(logits,labels)\n",
    "    \n",
    "    def predict_step(self,batch,_):\n",
    "        \n",
    "        logits = self.model.generate(\n",
    "            batch['input_ids'],\n",
    "            num_beams=1,\n",
    "            max_length=128\n",
    "        )\n",
    "        \n",
    "        logits = logits.detach().cpu().numpy()\n",
    "        logits = [self.tokenizer.decode(ids, skip_special_tokens=True) for ids in logits]\n",
    "        return logits\n",
    "    \n",
    "    def on_validation_epoch_end(self):\n",
    "        f = self.avg_meter.calc_metrics()\n",
    "        self.log_dict(f)\n",
    "        print(f)\n",
    "        self.avg_meter.reset()\n",
    "            \n",
    "    def configure_optimizers(self):\n",
    "        optimizer_grouped_parameters = [\n",
    "            {\n",
    "                \"params\": [p for n, p in self.model.named_parameters()],\n",
    "                \"lr\":self.cfg.lr\n",
    "            },\n",
    "        ]\n",
    "        return torch.optim.AdamW(optimizer_grouped_parameters,\n",
    "                                 betas=self.cfg.betas,\n",
    "                                 weight_decay=self.cfg.weight_decay,\n",
    "                                 eps=self.cfg.eps)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "cfb5a6f6-a5fa-49ea-a092-382bc251f5de",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.\n"
     ]
    }
   ],
   "source": [
    "tokenizer = AutoTokenizer.from_pretrained(CFG.model)\n",
    "model = T5ForConditionalGeneration.from_pretrained(CFG.model)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "fe400e66-bb1a-4214-bfdb-223b1d7c37a6",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'char_acc': 0.8366820644254979,\n",
       " 'acc': 0.73865,\n",
       " 'corrent_part': 0.9897,\n",
       " 'tanimoto': 0.9862146335034755}"
      ]
     },
     "execution_count": 25,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "avg_meter = AverageMeter()\n",
    "avg_meter.update(dm.val_df['refs'].tolist(),dm.val_df['smiles'].tolist())\n",
    "avg_meter.calc_metrics()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "1dc9ed95-1d58-49c0-8ea4-65532b0f85bc",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "model_pl = PLModule(model,tokenizer).cuda()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "9b8ad484-6d4f-41bb-893e-f8467fedf42e",
   "metadata": {},
   "outputs": [],
   "source": [
    "dm = PLDataModule(tokenizer)\n",
    "dm.prepare_data()\n",
    "dm.setup(0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "a9004596-1545-4514-98f0-0a9507e62735",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[34m\u001b[1mwandb\u001b[0m: Currently logged in as: \u001b[33mandrey20007\u001b[0m (\u001b[33mandrey2007\u001b[0m). Use \u001b[1m`wandb login --relogin`\u001b[0m to force relogin\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \u001b[33mWARNING\u001b[0m If you're specifying your api key in code, ensure this code is not shared publicly.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \u001b[33mWARNING\u001b[0m Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Appending key for api.wandb.ai to your netrc file: /root/.netrc\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "Changes to your `wandb` environment variables will be ignored because your `wandb` session has already started. For more information on how to modify your settings with `wandb.init()` arguments, please refer to <a href=\"https://wandb.me/wandb-init\" target=\"_blank\">the W&B docs</a>."
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "wandb version 0.16.1 is available!  To upgrade, please run:\n",
       " $ pip install wandb --upgrade"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Tracking run with wandb version 0.13.4"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Run data is saved locally in <code>/notebooks/wandb/run-20240102_155859-gmxjkzx3</code>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Syncing run <strong><a href=\"https://wandb.ai/andrey2007/MOLECULA/runs/gmxjkzx3\" target=\"_blank\">T5_Molscribe</a></strong> to <a href=\"https://wandb.ai/andrey2007/MOLECULA\" target=\"_blank\">Weights & Biases</a> (<a href=\"https://wandb.me/run\" target=\"_blank\">docs</a>)<br/>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<button onClick=\"this.nextSibling.style.display='block';this.style.display='none';\">Display W&B run</button><iframe src=\"https://wandb.ai/andrey2007/MOLECULA/runs/gmxjkzx3?jupyter=true\" style=\"border:none;width:100%;height:420px;display:none;\"></iframe>"
      ],
      "text/plain": [
       "<wandb.sdk.wandb_run.Run at 0x7f5a2e7a5be0>"
      ]
     },
     "execution_count": 28,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "wandb.login(key=\"673ae6e9b51cc896110db5327738b993795fffad\")\n",
    "os.environ['WANDB_API_KEY'] = \"673ae6e9b51cc896110db5327738b993795fffad\"\n",
    "wandb.init(project='MOLECULA',name='T5_Molscribe')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "029a5d24-64e8-412e-9d70-c2779554a158",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "GPU available: True (cuda), used: True\n",
      "TPU available: False, using: 0 TPU cores\n",
      "IPU available: False, using: 0 IPUs\n",
      "HPU available: False, using: 0 HPUs\n"
     ]
    }
   ],
   "source": [
    "lr_monitor = pl.callbacks.LearningRateMonitor(logging_interval='epoch')\n",
    "checkpoint_cb = pl.callbacks.ModelCheckpoint(\n",
    "    dirpath='./outputs/',\n",
    "    filename='base_model{epoch:02d}',\n",
    "    monitor='tanimoto',\n",
    "    mode='max',\n",
    "    save_last=True\n",
    ")\n",
    "\n",
    "trainer = pl.Trainer(\n",
    "    accelerator=\"gpu\",\n",
    "    precision=32,\n",
    "    callbacks = [lr_monitor,checkpoint_cb],\n",
    "    logger = pl.loggers.WandbLogger(),\n",
    "    min_epochs=1,\n",
    "    devices=[0],\n",
    "    check_val_every_n_epoch=1,\n",
    "    max_epochs=CFG.max_epoches\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fd64476d-2fc7-46df-a343-842ad89613d7",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "You are using a CUDA device ('NVIDIA A100-SXM4-80GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision\n",
      "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loggers/wandb.py:389: There is a wandb run already in progress and newly created instances of `WandbLogger` will reuse this run. If this is not desired, call `wandb.finish()` before instantiating `WandbLogger`.\n",
      "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/callbacks/model_checkpoint.py:639: Checkpoint directory /notebooks/outputs exists and is not empty.\n",
      "Restoring states from the checkpoint path at outputs/last.ckpt\n",
      "LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]\n",
      "\n",
      "  | Name  | Type                       | Params\n",
      "-----------------------------------------------------\n",
      "0 | model | T5ForConditionalGeneration | 198 M \n",
      "-----------------------------------------------------\n",
      "198 M     Trainable params\n",
      "0         Non-trainable params\n",
      "198 M     Total params\n",
      "794.275   Total estimated model params size (MB)\n",
      "Restored all states from the checkpoint at outputs/last.ckpt\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Sanity Checking: |          | 0/? [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'char_acc': 0.8726232447165678, 'acc': 0.796875, 'corrent_part': 0.984375, 'tanimoto': 0.8978899581373574}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "terminate called after throwing an instance of 'c10::CUDAError'\n",
      "  what():  CUDA error: initialization error\n",
      "CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\n",
      "For debugging consider passing CUDA_LAUNCH_BLOCKING=1.\n",
      "Exception raised from getDevice at ../c10/cuda/impl/CUDAGuardImpl.h:39 (most recent call first):\n",
      "frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x3e (0x7f5a1885f20e in /usr/local/lib/python3.9/dist-packages/torch/lib/libc10.so)\n",
      "frame #1: <unknown function> + 0x14660d (0x7f59e68a860d in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cuda_cpp.so)\n",
      "frame #2: <unknown function> + 0x149a9e (0x7f59e68aba9e in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cuda_cpp.so)\n",
      "frame #3: <unknown function> + 0x466778 (0x7f5a18e40778 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #4: c10::TensorImpl::release_resources() + 0x175 (0x7f5a188467a5 in /usr/local/lib/python3.9/dist-packages/torch/lib/libc10.so)\n",
      "frame #5: <unknown function> + 0x362795 (0x7f5a18d3c795 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #6: <unknown function> + 0x67c178 (0x7f5a19056178 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #7: THPVariable_subclass_dealloc(_object*) + 0x2b5 (0x7f5a19056525 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #8: /usr/local/bin/python3() [0x605cd0]\n",
      "frame #9: /usr/local/bin/python3() [0x620690]\n",
      "frame #10: /usr/local/bin/python3() [0x620781]\n",
      "frame #11: /usr/local/bin/python3() [0x620781]\n",
      "frame #12: /usr/local/bin/python3() [0x620781]\n",
      "frame #13: /usr/local/bin/python3() [0x620781]\n",
      "frame #14: /usr/local/bin/python3() [0x620781]\n",
      "frame #15: /usr/local/bin/python3() [0x620781]\n",
      "frame #16: /usr/local/bin/python3() [0x620781]\n",
      "frame #17: /usr/local/bin/python3() [0x620781]\n",
      "frame #18: /usr/local/bin/python3() [0x620781]\n",
      "frame #19: /usr/local/bin/python3() [0x620781]\n",
      "frame #20: /usr/local/bin/python3() [0x620781]\n",
      "frame #21: /usr/local/bin/python3() [0x620781]\n",
      "frame #22: /usr/local/bin/python3() [0x620781]\n",
      "frame #23: /usr/local/bin/python3() [0x620781]\n",
      "frame #24: /usr/local/bin/python3() [0x620781]\n",
      "frame #25: /usr/local/bin/python3() [0x620781]\n",
      "frame #26: /usr/local/bin/python3() [0x620781]\n",
      "frame #27: /usr/local/bin/python3() [0x620781]\n",
      "frame #28: /usr/local/bin/python3() [0x620781]\n",
      "frame #29: /usr/local/bin/python3() [0x620781]\n",
      "frame #30: /usr/local/bin/python3() [0x620781]\n",
      "frame #31: /usr/local/bin/python3() [0x620781]\n",
      "frame #32: /usr/local/bin/python3() [0x620781]\n",
      "frame #33: /usr/local/bin/python3() [0x620781]\n",
      "frame #34: /usr/local/bin/python3() [0x620781]\n",
      "frame #35: /usr/local/bin/python3() [0x620781]\n",
      "frame #36: /usr/local/bin/python3() [0x620781]\n",
      "frame #37: /usr/local/bin/python3() [0x5890b6]\n",
      "frame #38: /usr/local/bin/python3() [0x627d76]\n",
      "frame #39: /usr/local/bin/python3() [0x57ed6b]\n",
      "frame #40: /usr/local/bin/python3() [0x6b2a9e]\n",
      "frame #41: _PyObject_GC_New + 0x1eb (0x57dd8b in /usr/local/bin/python3)\n",
      "frame #42: /usr/local/bin/python3() [0x5dc165]\n",
      "frame #43: PyObject_GetItem + 0x3b (0x55392b in /usr/local/bin/python3)\n",
      "frame #44: _PyEval_EvalFrameDefault + 0xa9a (0x5abc8a in /usr/local/bin/python3)\n",
      "frame #45: /usr/local/bin/python3() [0x62c1d3]\n",
      "frame #46: /usr/local/bin/python3() [0x5dbb8f]\n",
      "frame #47: PyObject_GetItem + 0x3b (0x55392b in /usr/local/bin/python3)\n",
      "frame #48: _PyEval_EvalFrameDefault + 0xa9a (0x5abc8a in /usr/local/bin/python3)\n",
      "frame #49: _PyFunction_Vectorcall + 0x404 (0x62c994 in /usr/local/bin/python3)\n",
      "frame #50: _PyEval_EvalFrameDefault + 0x39f (0x5ab58f in /usr/local/bin/python3)\n",
      "frame #51: _PyFunction_Vectorcall + 0x404 (0x62c994 in /usr/local/bin/python3)\n",
      "frame #52: _PyEval_EvalFrameDefault + 0x636 (0x5ab826 in /usr/local/bin/python3)\n",
      "frame #53: /usr/local/bin/python3() [0x62c1d3]\n",
      "frame #54: _PyFunction_Vectorcall + 0x7f (0x62c60f in /usr/local/bin/python3)\n",
      "frame #55: PyObject_Call + 0x1aa (0x62a0aa in /usr/local/bin/python3)\n",
      "frame #56: _PyEval_EvalFrameDefault + 0x3d2b (0x5aef1b in /usr/local/bin/python3)\n",
      "frame #57: /usr/local/bin/python3() [0x62c1d3]\n",
      "frame #58: _PyFunction_Vectorcall + 0x7f (0x62c60f in /usr/local/bin/python3)\n",
      "frame #59: _PyEval_EvalFrameDefault + 0x636 (0x5ab826 in /usr/local/bin/python3)\n",
      "frame #60: /usr/local/bin/python3() [0x5a9eb4]\n",
      "frame #61: /usr/local/bin/python3() [0x5483e1]\n",
      "frame #62: _PyEval_EvalFrameDefault + 0x1145 (0x5ac335 in /usr/local/bin/python3)\n",
      "frame #63: /usr/local/bin/python3() [0x62c1d3]\n",
      "\n",
      "terminate called after throwing an instance of 'c10::CUDAError'\n",
      "  what():  CUDA error: initialization error\n",
      "CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\n",
      "For debugging consider passing CUDA_LAUNCH_BLOCKING=1.\n",
      "Exception raised from getDevice at ../c10/cuda/impl/CUDAGuardImpl.h:39 (most recent call first):\n",
      "frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x3e (0x7f5a1885f20e in /usr/local/lib/python3.9/dist-packages/torch/lib/libc10.so)\n",
      "frame #1: <unknown function> + 0x14660d (0x7f59e68a860d in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cuda_cpp.so)\n",
      "frame #2: <unknown function> + 0x149a9e (0x7f59e68aba9e in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cuda_cpp.so)\n",
      "frame #3: <unknown function> + 0x466778 (0x7f5a18e40778 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #4: c10::TensorImpl::release_resources() + 0x175 (0x7f5a188467a5 in /usr/local/lib/python3.9/dist-packages/torch/lib/libc10.so)\n",
      "frame #5: <unknown function> + 0x362795 (0x7f5a18d3c795 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #6: <unknown function> + 0x67c178 (0x7f5a19056178 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #7: THPVariable_subclass_dealloc(_object*) + 0x2b5 (0x7f5a19056525 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #8: /usr/local/bin/python3() [0x605cd0]\n",
      "frame #9: /usr/local/bin/python3() [0x620690]\n",
      "frame #10: /usr/local/bin/python3() [0x620781]\n",
      "frame #11: /usr/local/bin/python3() [0x620781]\n",
      "frame #12: /usr/local/bin/python3() [0x620781]\n",
      "frame #13: /usr/local/bin/python3() [0x620781]\n",
      "frame #14: /usr/local/bin/python3() [0x620781]\n",
      "frame #15: /usr/local/bin/python3() [0x620781]\n",
      "frame #16: /usr/local/bin/python3() [0x620781]\n",
      "frame #17: /usr/local/bin/python3() [0x620781]\n",
      "frame #18: /usr/local/bin/python3() [0x620781]\n",
      "frame #19: /usr/local/bin/python3() [0x620781]\n",
      "frame #20: /usr/local/bin/python3() [0x620781]\n",
      "frame #21: /usr/local/bin/python3() [0x620781]\n",
      "frame #22: /usr/local/bin/python3() [0x620781]\n",
      "frame #23: /usr/local/bin/python3() [0x620781]\n",
      "frame #24: /usr/local/bin/python3() [0x620781]\n",
      "frame #25: /usr/local/bin/python3() [0x620781]\n",
      "frame #26: /usr/local/bin/python3() [0x620781]\n",
      "frame #27: /usr/local/bin/python3() [0x620781]\n",
      "frame #28: /usr/local/bin/python3() [0x620781]\n",
      "frame #29: /usr/local/bin/python3() [0x620781]\n",
      "frame #30: /usr/local/bin/python3() [0x620781]\n",
      "frame #31: /usr/local/bin/python3() [0x620781]\n",
      "frame #32: /usr/local/bin/python3() [0x620781]\n",
      "frame #33: /usr/local/bin/python3() [0x620781]\n",
      "frame #34: /usr/local/bin/python3() [0x620781]\n",
      "frame #35: /usr/local/bin/python3() [0x620781]\n",
      "frame #36: /usr/local/bin/python3() [0x620781]\n",
      "frame #37: /usr/local/bin/python3() [0x5890b6]\n",
      "frame #38: /usr/local/bin/python3() [0x627d76]\n",
      "frame #39: /usr/local/bin/python3() [0x57ed6b]\n",
      "frame #40: /usr/local/bin/python3() [0x6b2a9e]\n",
      "frame #41: /usr/local/bin/python3() [0x541fc2]\n",
      "frame #42: _PyObject_LookupSpecial + 0xaa (0x5e281a in /usr/local/bin/python3)\n",
      "frame #43: /usr/local/bin/python3() [0x537a20]\n",
      "frame #44: /usr/local/bin/python3() [0x53a9cf]\n",
      "frame #45: _PyEval_EvalFrameDefault + 0x39f (0x5ab58f in /usr/local/bin/python3)\n",
      "frame #46: /usr/local/bin/python3() [0x62c1d3]\n",
      "frame #47: _PyFunction_Vectorcall + 0x7f (0x62c60f in /usr/local/bin/python3)\n",
      "frame #48: _PyEval_EvalFrameDefault + 0x39f (0x5ab58f in /usr/local/bin/python3)\n",
      "frame #49: /usr/local/bin/python3() [0x5a9eb4]\n",
      "frame #50: /usr/local/bin/python3() [0x5483e1]\n",
      "frame #51: _PyEval_EvalFrameDefault + 0x1145 (0x5ac335 in /usr/local/bin/python3)\n",
      "frame #52: _PyFunction_Vectorcall + 0x404 (0x62c994 in /usr/local/bin/python3)\n",
      "frame #53: /usr/local/bin/python3() [0x5d8076]\n",
      "frame #54: _PyObject_MakeTpCall + 0x3a3 (0x62a523 in /usr/local/bin/python3)\n",
      "frame #55: _PyEval_EvalFrameDefault + 0x5314 (0x5b0504 in /usr/local/bin/python3)\n",
      "frame #56: /usr/local/bin/python3() [0x5a9eb4]\n",
      "frame #57: /usr/local/bin/python3() [0x5483e1]\n",
      "frame #58: PyObject_Call + 0xac (0x629fac in /usr/local/bin/python3)\n",
      "frame #59: _PyEval_EvalFrameDefault + 0x3d2b (0x5aef1b in /usr/local/bin/python3)\n",
      "frame #60: /usr/local/bin/python3() [0x5a9eb4]\n",
      "frame #61: /usr/local/bin/python3() [0x5483e1]\n",
      "frame #62: PyObject_Call + 0xac (0x629fac in /usr/local/bin/python3)\n",
      "frame #63: _PyEval_EvalFrameDefault + 0x3d2b (0x5aef1b in /usr/local/bin/python3)\n",
      "\n",
      "terminate called after throwing an instance of 'c10::CUDAError'\n",
      "  what():  CUDA error: initialization error\n",
      "CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\n",
      "For debugging consider passing CUDA_LAUNCH_BLOCKING=1.\n",
      "Exception raised from getDevice at ../c10/cuda/impl/CUDAGuardImpl.h:39 (most recent call first):\n",
      "frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x3e (0x7f5a1885f20e in /usr/local/lib/python3.9/dist-packages/torch/lib/libc10.so)\n",
      "frame #1: <unknown function> + 0x14660d (0x7f59e68a860d in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cuda_cpp.so)\n",
      "frame #2: <unknown function> + 0x149a9e (0x7f59e68aba9e in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cuda_cpp.so)\n",
      "frame #3: <unknown function> + 0x466778 (0x7f5a18e40778 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #4: c10::TensorImpl::release_resources() + 0x175 (0x7f5a188467a5 in /usr/local/lib/python3.9/dist-packages/torch/lib/libc10.so)\n",
      "frame #5: <unknown function> + 0x362795 (0x7f5a18d3c795 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #6: <unknown function> + 0x67c178 (0x7f5a19056178 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #7: THPVariable_subclass_dealloc(_object*) + 0x2b5 (0x7f5a19056525 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #8: /usr/local/bin/python3() [0x605cd0]\n",
      "frame #9: /usr/local/bin/python3() [0x620690]\n",
      "frame #10: /usr/local/bin/python3() [0x620781]\n",
      "frame #11: /usr/local/bin/python3() [0x620781]\n",
      "frame #12: /usr/local/bin/python3() [0x620781]\n",
      "frame #13: /usr/local/bin/python3() [0x620781]\n",
      "frame #14: /usr/local/bin/python3() [0x620781]\n",
      "frame #15: /usr/local/bin/python3() [0x620781]\n",
      "frame #16: /usr/local/bin/python3() [0x620781]\n",
      "frame #17: /usr/local/bin/python3() [0x620781]\n",
      "frame #18: /usr/local/bin/python3() [0x620781]\n",
      "frame #19: /usr/local/bin/python3() [0x620781]\n",
      "frame #20: /usr/local/bin/python3() [0x620781]\n",
      "frame #21: /usr/local/bin/python3() [0x620781]\n",
      "frame #22: /usr/local/bin/python3() [0x620781]\n",
      "frame #23: /usr/local/bin/python3() [0x620781]\n",
      "frame #24: /usr/local/bin/python3() [0x620781]\n",
      "frame #25: /usr/local/bin/python3() [0x620781]\n",
      "frame #26: /usr/local/bin/python3() [0x620781]\n",
      "frame #27: /usr/local/bin/python3() [0x620781]\n",
      "frame #28: /usr/local/bin/python3() [0x620781]\n",
      "frame #29: /usr/local/bin/python3() [0x620781]\n",
      "frame #30: /usr/local/bin/python3() [0x620781]\n",
      "frame #31: /usr/local/bin/python3() [0x620781]\n",
      "frame #32: /usr/local/bin/python3() [0x620781]\n",
      "frame #33: /usr/local/bin/python3() [0x620781]\n",
      "frame #34: /usr/local/bin/python3() [0x620781]\n",
      "frame #35: /usr/local/bin/python3() [0x620781]\n",
      "frame #36: /usr/local/bin/python3() [0x620781]\n",
      "frame #37: /usr/local/bin/python3() [0x5890b6]\n",
      "frame #38: /usr/local/bin/python3() [0x627d76]\n",
      "frame #39: /usr/local/bin/python3() [0x57ed6b]\n",
      "frame #40: /usr/local/bin/python3() [0x6b2a9e]\n",
      "frame #41: /usr/local/bin/python3() [0x61aa17]\n",
      "frame #42: /usr/local/bin/python3() [0x644765]\n",
      "frame #43: /usr/local/bin/python3() [0x6adbee]\n",
      "frame #44: /usr/local/bin/python3() [0x53aac7]\n",
      "frame #45: /usr/local/bin/python3() [0x537bf3]\n",
      "frame #46: /usr/local/bin/python3() [0x604347]\n",
      "frame #47: PyObject_GetItem + 0x3b (0x55392b in /usr/local/bin/python3)\n",
      "frame #48: _PyEval_EvalFrameDefault + 0xa9a (0x5abc8a in /usr/local/bin/python3)\n",
      "frame #49: /usr/local/bin/python3() [0x5a9eb4]\n",
      "frame #50: /usr/local/bin/python3() [0x5483e1]\n",
      "frame #51: _PyEval_EvalFrameDefault + 0x1145 (0x5ac335 in /usr/local/bin/python3)\n",
      "frame #52: _PyFunction_Vectorcall + 0x404 (0x62c994 in /usr/local/bin/python3)\n",
      "frame #53: _PyEval_EvalFrameDefault + 0x39f (0x5ab58f in /usr/local/bin/python3)\n",
      "frame #54: /usr/local/bin/python3() [0x5a9eb4]\n",
      "frame #55: /usr/local/bin/python3() [0x5483e1]\n",
      "frame #56: PyObject_Call + 0xac (0x629fac in /usr/local/bin/python3)\n",
      "frame #57: _PyEval_EvalFrameDefault + 0x3d2b (0x5aef1b in /usr/local/bin/python3)\n",
      "frame #58: /usr/local/bin/python3() [0x5a9eb4]\n",
      "frame #59: /usr/local/bin/python3() [0x5483e1]\n",
      "frame #60: PyObject_Call + 0xac (0x629fac in /usr/local/bin/python3)\n",
      "frame #61: _PyEval_EvalFrameDefault + 0x3d2b (0x5aef1b in /usr/local/bin/python3)\n",
      "frame #62: /usr/local/bin/python3() [0x5a9eb4]\n",
      "frame #63: /usr/local/bin/python3() [0x5483e1]\n",
      "\n",
      "terminate called after throwing an instance of 'c10::CUDAError'\n",
      "  what():  CUDA error: initialization error\n",
      "CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\n",
      "For debugging consider passing CUDA_LAUNCH_BLOCKING=1.\n",
      "Exception raised from getDevice at ../c10/cuda/impl/CUDAGuardImpl.h:39 (most recent call first):\n",
      "frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x3e (0x7f5a1885f20e in /usr/local/lib/python3.9/dist-packages/torch/lib/libc10.so)\n",
      "frame #1: <unknown function> + 0x14660d (0x7f59e68a860d in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cuda_cpp.so)\n",
      "frame #2: <unknown function> + 0x149a9e (0x7f59e68aba9e in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cuda_cpp.so)\n",
      "frame #3: <unknown function> + 0x466778 (0x7f5a18e40778 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #4: c10::TensorImpl::release_resources() + 0x175 (0x7f5a188467a5 in /usr/local/lib/python3.9/dist-packages/torch/lib/libc10.so)\n",
      "frame #5: <unknown function> + 0x362795 (0x7f5a18d3c795 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #6: <unknown function> + 0x67c178 (0x7f5a19056178 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #7: THPVariable_subclass_dealloc(_object*) + 0x2b5 (0x7f5a19056525 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #8: /usr/local/bin/python3() [0x605cd0]\n",
      "frame #9: /usr/local/bin/python3() [0x620690]\n",
      "frame #10: /usr/local/bin/python3() [0x620781]\n",
      "frame #11: /usr/local/bin/python3() [0x620781]\n",
      "frame #12: /usr/local/bin/python3() [0x620781]\n",
      "frame #13: /usr/local/bin/python3() [0x620781]\n",
      "frame #14: /usr/local/bin/python3() [0x620781]\n",
      "frame #15: /usr/local/bin/python3() [0x620781]\n",
      "frame #16: /usr/local/bin/python3() [0x620781]\n",
      "frame #17: /usr/local/bin/python3() [0x620781]\n",
      "frame #18: /usr/local/bin/python3() [0x620781]\n",
      "frame #19: /usr/local/bin/python3() [0x620781]\n",
      "frame #20: /usr/local/bin/python3() [0x620781]\n",
      "frame #21: /usr/local/bin/python3() [0x620781]\n",
      "frame #22: /usr/local/bin/python3() [0x620781]\n",
      "frame #23: /usr/local/bin/python3() [0x620781]\n",
      "frame #24: /usr/local/bin/python3() [0x620781]\n",
      "frame #25: /usr/local/bin/python3() [0x620781]\n",
      "frame #26: /usr/local/bin/python3() [0x620781]\n",
      "frame #27: /usr/local/bin/python3() [0x620781]\n",
      "frame #28: /usr/local/bin/python3() [0x620781]\n",
      "frame #29: /usr/local/bin/python3() [0x620781]\n",
      "frame #30: /usr/local/bin/python3() [0x620781]\n",
      "frame #31: /usr/local/bin/python3() [0x620781]\n",
      "frame #32: /usr/local/bin/python3() [0x620781]\n",
      "frame #33: /usr/local/bin/python3() [0x620781]\n",
      "frame #34: /usr/local/bin/python3() [0x620781]\n",
      "frame #35: /usr/local/bin/python3() [0x620781]\n",
      "frame #36: /usr/local/bin/python3() [0x620781]\n",
      "frame #37: /usr/local/bin/python3() [0x5890b6]\n",
      "frame #38: /usr/local/bin/python3() [0x627d76]\n",
      "frame #39: /usr/local/bin/python3() [0x57ed6b]\n",
      "frame #40: /usr/local/bin/python3() [0x6b2a9e]\n",
      "frame #41: /usr/local/bin/python3() [0x541fc2]\n",
      "frame #42: _PyObject_LookupSpecial + 0xaa (0x5e281a in /usr/local/bin/python3)\n",
      "frame #43: /usr/local/bin/python3() [0x537a20]\n",
      "frame #44: /usr/local/bin/python3() [0x53a9cf]\n",
      "frame #45: _PyEval_EvalFrameDefault + 0x39f (0x5ab58f in /usr/local/bin/python3)\n",
      "frame #46: /usr/local/bin/python3() [0x62c1d3]\n",
      "frame #47: _PyFunction_Vectorcall + 0x7f (0x62c60f in /usr/local/bin/python3)\n",
      "frame #48: _PyEval_EvalFrameDefault + 0x39f (0x5ab58f in /usr/local/bin/python3)\n",
      "frame #49: /usr/local/bin/python3() [0x5a9eb4]\n",
      "frame #50: /usr/local/bin/python3() [0x5483e1]\n",
      "frame #51: _PyEval_EvalFrameDefault + 0x1145 (0x5ac335 in /usr/local/bin/python3)\n",
      "frame #52: _PyFunction_Vectorcall + 0x404 (0x62c994 in /usr/local/bin/python3)\n",
      "frame #53: /usr/local/bin/python3() [0x5d8076]\n",
      "frame #54: _PyObject_MakeTpCall + 0x3a3 (0x62a523 in /usr/local/bin/python3)\n",
      "frame #55: _PyEval_EvalFrameDefault + 0x5314 (0x5b0504 in /usr/local/bin/python3)\n",
      "frame #56: /usr/local/bin/python3() [0x5a9eb4]\n",
      "frame #57: /usr/local/bin/python3() [0x5483e1]\n",
      "frame #58: PyObject_Call + 0xac (0x629fac in /usr/local/bin/python3)\n",
      "frame #59: _PyEval_EvalFrameDefault + 0x3d2b (0x5aef1b in /usr/local/bin/python3)\n",
      "frame #60: /usr/local/bin/python3() [0x5a9eb4]\n",
      "frame #61: /usr/local/bin/python3() [0x5483e1]\n",
      "frame #62: PyObject_Call + 0xac (0x629fac in /usr/local/bin/python3)\n",
      "frame #63: _PyEval_EvalFrameDefault + 0x3d2b (0x5aef1b in /usr/local/bin/python3)\n",
      "\n",
      "terminate called after throwing an instance of 'c10::CUDAError'\n",
      "  what():  CUDA error: initialization error\n",
      "CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\n",
      "For debugging consider passing CUDA_LAUNCH_BLOCKING=1.\n",
      "Exception raised from getDevice at ../c10/cuda/impl/CUDAGuardImpl.h:39 (most recent call first):\n",
      "frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x3e (0x7f5a1885f20e in /usr/local/lib/python3.9/dist-packages/torch/lib/libc10.so)\n",
      "frame #1: <unknown function> + 0x14660d (0x7f59e68a860d in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cuda_cpp.so)\n",
      "frame #2: <unknown function> + 0x149a9e (0x7f59e68aba9e in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cuda_cpp.so)\n",
      "frame #3: <unknown function> + 0x466778 (0x7f5a18e40778 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #4: c10::TensorImpl::release_resources() + 0x175 (0x7f5a188467a5 in /usr/local/lib/python3.9/dist-packages/torch/lib/libc10.so)\n",
      "frame #5: <unknown function> + 0x362795 (0x7f5a18d3c795 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #6: <unknown function> + 0x67c178 (0x7f5a19056178 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #7: THPVariable_subclass_dealloc(_object*) + 0x2b5 (0x7f5a19056525 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #8: /usr/local/bin/python3() [0x605cd0]\n",
      "frame #9: /usr/local/bin/python3() [0x620690]\n",
      "frame #10: /usr/local/bin/python3() [0x620781]\n",
      "frame #11: /usr/local/bin/python3() [0x620781]\n",
      "frame #12: /usr/local/bin/python3() [0x620781]\n",
      "frame #13: /usr/local/bin/python3() [0x620781]\n",
      "frame #14: /usr/local/bin/python3() [0x620781]\n",
      "frame #15: /usr/local/bin/python3() [0x620781]\n",
      "frame #16: /usr/local/bin/python3() [0x620781]\n",
      "frame #17: /usr/local/bin/python3() [0x620781]\n",
      "frame #18: /usr/local/bin/python3() [0x620781]\n",
      "frame #19: /usr/local/bin/python3() [0x620781]\n",
      "frame #20: /usr/local/bin/python3() [0x620781]\n",
      "frame #21: /usr/local/bin/python3() [0x620781]\n",
      "frame #22: /usr/local/bin/python3() [0x620781]\n",
      "frame #23: /usr/local/bin/python3() [0x620781]\n",
      "frame #24: /usr/local/bin/python3() [0x620781]\n",
      "frame #25: /usr/local/bin/python3() [0x620781]\n",
      "frame #26: /usr/local/bin/python3() [0x620781]\n",
      "frame #27: /usr/local/bin/python3() [0x620781]\n",
      "frame #28: /usr/local/bin/python3() [0x620781]\n",
      "frame #29: /usr/local/bin/python3() [0x620781]\n",
      "frame #30: /usr/local/bin/python3() [0x620781]\n",
      "frame #31: /usr/local/bin/python3() [0x620781]\n",
      "frame #32: /usr/local/bin/python3() [0x620781]\n",
      "frame #33: /usr/local/bin/python3() [0x620781]\n",
      "frame #34: /usr/local/bin/python3() [0x620781]\n",
      "frame #35: /usr/local/bin/python3() [0x620781]\n",
      "frame #36: /usr/local/bin/python3() [0x620781]\n",
      "frame #37: /usr/local/bin/python3() [0x5890b6]\n",
      "frame #38: /usr/local/bin/python3() [0x627d76]\n",
      "frame #39: /usr/local/bin/python3() [0x57ed6b]\n",
      "frame #40: /usr/local/bin/python3() [0x6b2a9e]\n",
      "frame #41: _PyObject_GC_New + 0x1eb (0x57dd8b in /usr/local/bin/python3)\n",
      "frame #42: _PyDictView_New + 0x2d (0x5fba1d in /usr/local/bin/python3)\n",
      "frame #43: /usr/local/bin/python3() [0x53f905]\n",
      "frame #44: _PyEval_EvalFrameDefault + 0x636 (0x5ab826 in /usr/local/bin/python3)\n",
      "frame #45: /usr/local/bin/python3() [0x62c1d3]\n",
      "frame #46: /usr/local/bin/python3() [0x5482c4]\n",
      "frame #47: _PyEval_EvalFrameDefault + 0x4b11 (0x5afd01 in /usr/local/bin/python3)\n",
      "frame #48: /usr/local/bin/python3() [0x5a9eb4]\n",
      "frame #49: /usr/local/bin/python3() [0x5483e1]\n",
      "frame #50: _PyEval_EvalFrameDefault + 0x1145 (0x5ac335 in /usr/local/bin/python3)\n",
      "frame #51: _PyFunction_Vectorcall + 0x404 (0x62c994 in /usr/local/bin/python3)\n",
      "frame #52: /usr/local/bin/python3() [0x5d8076]\n",
      "frame #53: _PyObject_MakeTpCall + 0x3a3 (0x62a523 in /usr/local/bin/python3)\n",
      "frame #54: _PyEval_EvalFrameDefault + 0x5314 (0x5b0504 in /usr/local/bin/python3)\n",
      "frame #55: /usr/local/bin/python3() [0x5a9eb4]\n",
      "frame #56: /usr/local/bin/python3() [0x5483e1]\n",
      "frame #57: PyObject_Call + 0xac (0x629fac in /usr/local/bin/python3)\n",
      "frame #58: _PyEval_EvalFrameDefault + 0x3d2b (0x5aef1b in /usr/local/bin/python3)\n",
      "frame #59: /usr/local/bin/python3() [0x5a9eb4]\n",
      "frame #60: /usr/local/bin/python3() [0x5483e1]\n",
      "frame #61: PyObject_Call + 0xac (0x629fac in /usr/local/bin/python3)\n",
      "frame #62: _PyEval_EvalFrameDefault + 0x3d2b (0x5aef1b in /usr/local/bin/python3)\n",
      "frame #63: /usr/local/bin/python3() [0x5a9eb4]\n",
      "\n",
      "terminate called after throwing an instance of 'c10::CUDAError'\n",
      "  what():  CUDA error: initialization error\n",
      "CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\n",
      "For debugging consider passing CUDA_LAUNCH_BLOCKING=1.\n",
      "Exception raised from getDevice at ../c10/cuda/impl/CUDAGuardImpl.h:39 (most recent call first):\n",
      "frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x3e (0x7f5a1885f20e in /usr/local/lib/python3.9/dist-packages/torch/lib/libc10.so)\n",
      "frame #1: <unknown function> + 0x14660d (0x7f59e68a860d in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cuda_cpp.so)\n",
      "frame #2: <unknown function> + 0x149a9e (0x7f59e68aba9e in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cuda_cpp.so)\n",
      "frame #3: <unknown function> + 0x466778 (0x7f5a18e40778 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #4: c10::TensorImpl::release_resources() + 0x175 (0x7f5a188467a5 in /usr/local/lib/python3.9/dist-packages/torch/lib/libc10.so)\n",
      "frame #5: <unknown function> + 0x362795 (0x7f5a18d3c795 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #6: <unknown function> + 0x67c178 (0x7f5a19056178 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #7: THPVariable_subclass_dealloc(_object*) + 0x2b5 (0x7f5a19056525 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #8: /usr/local/bin/python3() [0x605cd0]\n",
      "frame #9: /usr/local/bin/python3() [0x620690]\n",
      "frame #10: /usr/local/bin/python3() [0x620781]\n",
      "frame #11: /usr/local/bin/python3() [0x620781]\n",
      "frame #12: /usr/local/bin/python3() [0x620781]\n",
      "frame #13: /usr/local/bin/python3() [0x620781]\n",
      "frame #14: /usr/local/bin/python3() [0x620781]\n",
      "frame #15: /usr/local/bin/python3() [0x620781]\n",
      "frame #16: /usr/local/bin/python3() [0x620781]\n",
      "frame #17: /usr/local/bin/python3() [0x620781]\n",
      "frame #18: /usr/local/bin/python3() [0x620781]\n",
      "frame #19: /usr/local/bin/python3() [0x620781]\n",
      "frame #20: /usr/local/bin/python3() [0x620781]\n",
      "frame #21: /usr/local/bin/python3() [0x620781]\n",
      "frame #22: /usr/local/bin/python3() [0x620781]\n",
      "frame #23: /usr/local/bin/python3() [0x620781]\n",
      "frame #24: /usr/local/bin/python3() [0x620781]\n",
      "frame #25: /usr/local/bin/python3() [0x620781]\n",
      "frame #26: /usr/local/bin/python3() [0x620781]\n",
      "frame #27: /usr/local/bin/python3() [0x620781]\n",
      "frame #28: /usr/local/bin/python3() [0x620781]\n",
      "frame #29: /usr/local/bin/python3() [0x620781]\n",
      "frame #30: /usr/local/bin/python3() [0x620781]\n",
      "frame #31: /usr/local/bin/python3() [0x620781]\n",
      "frame #32: /usr/local/bin/python3() [0x620781]\n",
      "frame #33: /usr/local/bin/python3() [0x620781]\n",
      "frame #34: /usr/local/bin/python3() [0x620781]\n",
      "frame #35: /usr/local/bin/python3() [0x620781]\n",
      "frame #36: /usr/local/bin/python3() [0x620781]\n",
      "frame #37: /usr/local/bin/python3() [0x5890b6]\n",
      "frame #38: /usr/local/bin/python3() [0x627d76]\n",
      "frame #39: /usr/local/bin/python3() [0x57ed6b]\n",
      "frame #40: /usr/local/bin/python3() [0x6b2a9e]\n",
      "frame #41: /usr/local/bin/python3() [0x53c49f]\n",
      "frame #42: PyObject_GetAttr + 0x33a (0x5fa4aa in /usr/local/bin/python3)\n",
      "frame #43: _PyEval_EvalFrameDefault + 0x707 (0x5ab8f7 in /usr/local/bin/python3)\n",
      "frame #44: /usr/local/bin/python3() [0x5a9eb4]\n",
      "frame #45: /usr/local/bin/python3() [0x5483e1]\n",
      "frame #46: PyObject_Call + 0xac (0x629fac in /usr/local/bin/python3)\n",
      "frame #47: _PyEval_EvalFrameDefault + 0x3d2b (0x5aef1b in /usr/local/bin/python3)\n",
      "frame #48: /usr/local/bin/python3() [0x5a9eb4]\n",
      "frame #49: /usr/local/bin/python3() [0x5483e1]\n",
      "frame #50: PyObject_Call + 0xac (0x629fac in /usr/local/bin/python3)\n",
      "frame #51: _PyEval_EvalFrameDefault + 0x3d2b (0x5aef1b in /usr/local/bin/python3)\n",
      "frame #52: /usr/local/bin/python3() [0x5a9eb4]\n",
      "frame #53: /usr/local/bin/python3() [0x5483e1]\n",
      "frame #54: _PyEval_EvalFrameDefault + 0x1145 (0x5ac335 in /usr/local/bin/python3)\n",
      "frame #55: /usr/local/bin/python3() [0x62c1d3]\n",
      "frame #56: /usr/local/bin/python3() [0x5dbb8f]\n",
      "frame #57: PyObject_GetItem + 0x3b (0x55392b in /usr/local/bin/python3)\n",
      "frame #58: _PyEval_EvalFrameDefault + 0xa9a (0x5abc8a in /usr/local/bin/python3)\n",
      "frame #59: _PyFunction_Vectorcall + 0x404 (0x62c994 in /usr/local/bin/python3)\n",
      "frame #60: _PyEval_EvalFrameDefault + 0x39f (0x5ab58f in /usr/local/bin/python3)\n",
      "frame #61: _PyFunction_Vectorcall + 0x404 (0x62c994 in /usr/local/bin/python3)\n",
      "frame #62: _PyEval_EvalFrameDefault + 0x636 (0x5ab826 in /usr/local/bin/python3)\n",
      "frame #63: /usr/local/bin/python3() [0x62c1d3]\n",
      "\n",
      "terminate called after throwing an instance of 'c10::CUDAError'\n",
      "  what():  CUDA error: initialization error\n",
      "CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\n",
      "For debugging consider passing CUDA_LAUNCH_BLOCKING=1.\n",
      "Exception raised from getDevice at ../c10/cuda/impl/CUDAGuardImpl.h:39 (most recent call first):\n",
      "frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x3e (0x7f5a1885f20e in /usr/local/lib/python3.9/dist-packages/torch/lib/libc10.so)\n",
      "frame #1: <unknown function> + 0x14660d (0x7f59e68a860d in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cuda_cpp.so)\n",
      "frame #2: <unknown function> + 0x149a9e (0x7f59e68aba9e in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_cuda_cpp.so)\n",
      "frame #3: <unknown function> + 0x466778 (0x7f5a18e40778 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #4: c10::TensorImpl::release_resources() + 0x175 (0x7f5a188467a5 in /usr/local/lib/python3.9/dist-packages/torch/lib/libc10.so)\n",
      "frame #5: <unknown function> + 0x362795 (0x7f5a18d3c795 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #6: <unknown function> + 0x67c178 (0x7f5a19056178 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #7: THPVariable_subclass_dealloc(_object*) + 0x2b5 (0x7f5a19056525 in /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so)\n",
      "frame #8: /usr/local/bin/python3() [0x605cd0]\n",
      "frame #9: /usr/local/bin/python3() [0x620690]\n",
      "frame #10: /usr/local/bin/python3() [0x620781]\n",
      "frame #11: /usr/local/bin/python3() [0x620781]\n",
      "frame #12: /usr/local/bin/python3() [0x620781]\n",
      "frame #13: /usr/local/bin/python3() [0x620781]\n",
      "frame #14: /usr/local/bin/python3() [0x620781]\n",
      "frame #15: /usr/local/bin/python3() [0x620781]\n",
      "frame #16: /usr/local/bin/python3() [0x620781]\n",
      "frame #17: /usr/local/bin/python3() [0x620781]\n",
      "frame #18: /usr/local/bin/python3() [0x620781]\n",
      "frame #19: /usr/local/bin/python3() [0x620781]\n",
      "frame #20: /usr/local/bin/python3() [0x620781]\n",
      "frame #21: /usr/local/bin/python3() [0x620781]\n",
      "frame #22: /usr/local/bin/python3() [0x620781]\n",
      "frame #23: /usr/local/bin/python3() [0x620781]\n",
      "frame #24: /usr/local/bin/python3() [0x620781]\n",
      "frame #25: /usr/local/bin/python3() [0x620781]\n",
      "frame #26: /usr/local/bin/python3() [0x620781]\n",
      "frame #27: /usr/local/bin/python3() [0x620781]\n",
      "frame #28: /usr/local/bin/python3() [0x620781]\n",
      "frame #29: /usr/local/bin/python3() [0x620781]\n",
      "frame #30: /usr/local/bin/python3() [0x620781]\n",
      "frame #31: /usr/local/bin/python3() [0x620781]\n",
      "frame #32: /usr/local/bin/python3() [0x620781]\n",
      "frame #33: /usr/local/bin/python3() [0x620781]\n",
      "frame #34: /usr/local/bin/python3() [0x620781]\n",
      "frame #35: /usr/local/bin/python3() [0x620781]\n",
      "frame #36: /usr/local/bin/python3() [0x620781]\n",
      "frame #37: /usr/local/bin/python3() [0x5890b6]\n",
      "frame #38: /usr/local/bin/python3() [0x627d76]\n",
      "frame #39: /usr/local/bin/python3() [0x57ed6b]\n",
      "frame #40: /usr/local/bin/python3() [0x6b2a9e]\n",
      "frame #41: /usr/local/bin/python3() [0x53c49f]\n",
      "frame #42: /usr/local/bin/python3() [0x5d7392]\n",
      "frame #43: PyObject_GetAttr + 0x282 (0x5fa3f2 in /usr/local/bin/python3)\n",
      "frame #44: _PyObject_GetMethod + 0x21b (0x5fa90b in /usr/local/bin/python3)\n",
      "frame #45: _PyEval_EvalFrameDefault + 0x538 (0x5ab728 in /usr/local/bin/python3)\n",
      "frame #46: /usr/local/bin/python3() [0x5a9eb4]\n",
      "frame #47: /usr/local/bin/python3() [0x5483e1]\n",
      "frame #48: _PyEval_EvalFrameDefault + 0x1145 (0x5ac335 in /usr/local/bin/python3)\n",
      "frame #49: _PyFunction_Vectorcall + 0x404 (0x62c994 in /usr/local/bin/python3)\n",
      "frame #50: /usr/local/bin/python3() [0x5d8076]\n",
      "frame #51: _PyObject_MakeTpCall + 0x3a3 (0x62a523 in /usr/local/bin/python3)\n",
      "frame #52: _PyEval_EvalFrameDefault + 0x5314 (0x5b0504 in /usr/local/bin/python3)\n",
      "frame #53: /usr/local/bin/python3() [0x5a9eb4]\n",
      "frame #54: /usr/local/bin/python3() [0x5483e1]\n",
      "frame #55: PyObject_Call + 0xac (0x629fac in /usr/local/bin/python3)\n",
      "frame #56: _PyEval_EvalFrameDefault + 0x3d2b (0x5aef1b in /usr/local/bin/python3)\n",
      "frame #57: /usr/local/bin/python3() [0x5a9eb4]\n",
      "frame #58: /usr/local/bin/python3() [0x5483e1]\n",
      "frame #59: PyObject_Call + 0xac (0x629fac in /usr/local/bin/python3)\n",
      "frame #60: _PyEval_EvalFrameDefault + 0x3d2b (0x5aef1b in /usr/local/bin/python3)\n",
      "frame #61: /usr/local/bin/python3() [0x5a9eb4]\n",
      "frame #62: /usr/local/bin/python3() [0x5483e1]\n",
      "frame #63: _PyEval_EvalFrameDefault + 0x1145 (0x5ac335 in /usr/local/bin/python3)\n",
      "\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "e6fac98eb98a4d81a717ada024e26bb7",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Training: |          | 0/? [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function _releaseLock at 0x7f5a6d262d30>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.9/logging/__init__.py\", line 227, in _releaseLock\n",
      "    def _releaseLock():\n",
      "  File \"/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/signal_handling.py\", line 66, in handler\n",
      "    _error_if_any_worker_fails()\n",
      "RuntimeError: DataLoader worker (pid 7321) is killed by signal: Aborted. \n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Validation: |          | 0/? [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'char_acc': 0.8397013068764191, 'acc': 0.7376, 'corrent_part': 0.9512, 'tanimoto': 0.837901101010471}\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Validation: |          | 0/? [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'char_acc': 0.8411512589570728, 'acc': 0.7398, 'corrent_part': 0.9515, 'tanimoto': 0.8386412060402542}\n",
      "{'char_acc': 0.8409368748652861, 'acc': 0.7402, 'corrent_part': 0.95245, 'tanimoto': 0.8392765023845196}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "IOPub message rate exceeded.\n",
      "The Jupyter server will temporarily stop sending output\n",
      "to the client in order to avoid crashing it.\n",
      "To change this limit, set the config variable\n",
      "`--ServerApp.iopub_msg_rate_limit`.\n",
      "\n",
      "Current values:\n",
      "ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)\n",
      "ServerApp.rate_limit_window=3.0 (secs)\n",
      "\n"
     ]
    }
   ],
   "source": [
    "trainer.fit(model_pl,datamodule=dm,ckpt_path=\"outputs/last.ckpt\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f3688807-1399-48cc-8e5c-ae470626774a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
